### PR TITLE
Add another kick route

### PR DESCRIPTION
**Pull request by ghost**
Added ``PlayerKickRoute``:

``DEL`` **/player/kick**
``{{base}}/player/kick?{{player}}&reason=string&duration=int&async=bool``
Kicks a player based on one or more properties.

**Requirements**
- Requires Admin permission.

**Filters**
All query parameters are filters to the final result except for reason and duration. You can filter by cid, uuid, ip, username, nickname, and account. They are all optional.

**Response**
A ``PlayerKickResponse`` which has the following properties:
- **Players** - ``List<Player>``
All of the users which matched the query.
- **SuccessfulKicks** - ``int``
Number of users kicked successfully via RCON. Always 0 if async is enabled.
- **FailedKicks** - ``int``
Number of users who could not be kicked via RCON. Always 0 if async is enabled.

### Default Parameters
- **reason** - ``string``
_Default: Disconnected due to inactivity_
- **duration** - ``int?``
_Default: ``null`` (kicks normally with no timeout.)_
- **async** - ``bool``
_Default: false_

### Player Parameters
- **cid** - ``int``
_Optional: Filters players based off of the connection ID._
- **username** - ``string``
_Optional: Filters players based off of their username._
-  **nickname** - ``string``
_Optional: Filters players based off of their nickname, excluding those with no nickname._
- **account** - ``string``
_Optional: Filters players based off of their account name._
- **ip** - ``string``
_Optional: Filters players based off of their IP address._
- **uuid** - ``string``
_Optional: Filters players based off of their UUID, excluding those with no UUID._

### CODE REVIEW

**Comment by ghost** [comment]
@Lachee Not sure how I would go about updating docs on Postman, or if you would rather.

**Review by Lachee — COMMENTED** [review]
Why do we need another kick route?

**Comment by Lachee** [comment]
> @Lachee Not sure how I would go about updating docs on Postman, or if you would rather.

oh good point, i totally forgot about postman. TBH i dislike having to use postman now, so if you have alternatives (even perhaps writing a Swagger / OpenAPI 3.0 doc) i'll be open.

**Comment by ghost** [comment]
> Why do we need another kick route?

The old route is being used by a few things and only supports CID. Without a replacement for the DEL handler, it can't support queries that ask for other values. (Or it can but I'm not sure how to make it do that yet).

I'd rather have Starwatch do the query versus having to call Get /session before doing Del /player/:cid, since it'd be cheaper.

**Comment by ghost** [comment]
> > @Lachee Not sure how I would go about updating docs on Postman, or if you would rather.
> 
> oh good point, i totally forgot about postman. TBH i dislike having to use postman now, so if you have alternatives (even perhaps writing a Swagger / OpenAPI 3.0 doc) i'll be open.

Haven't used anything in the past so I'll look into that. 😅 Thanks

**Pull request merged**
